name: TAMULib Java Coverage Action
description: Build coverage for Java code for parallel coveralls execution.

inputs:
  version:
    description: 'The version of Java to use.'
    required: true
    default: 1.8
  build_number:
    description: 'The Unique Build Number for Coveralls.'
    required: true
  github_token:
    description: 'The API token for Github.'
    required: true

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v2

    - name: Setup JDK ${{ inputs.version }} (build ${{ inputs.build_number }})
      uses: actions/setup-java@v1
      env:
        COVERALLS_PARALLEL: true
        COVERALLS_BUILD_NUMBER: run-${{ inputs.build_number }}-java
        COVERALLS_REPO_TOKEN: ${{ inputs.coveralls_token }}
      run: |
        mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
        mvn clean test cobertura:cobertura jacoco:report coveralls:report -DserviceName="github-actions"

    - name: Coveralls Parallel Java (build ${{ inputs.build_number }})
      uses: coverallsapp/github-action@master
      with:
        github_token: ${{ inputs.github_token }}
        flag-name: run-${{ inputs.build_number }}-java
        parallel: true
