INSERT INTO INTERNAL_METADATA (ID, GLOSS, FIELD) VALUES (1, 'Id', 'id');
INSERT INTO INTERNAL_METADATA (ID, GLOSS, FIELD) VALUES (2, 'Title', 'title'); 
INSERT INTO INTERNAL_METADATA (ID, GLOSS, FIELD) VALUES (3, 'Creator', 'creator');
INSERT INTO INTERNAL_METADATA (ID, GLOSS, FIELD) VALUES (4, 'Created', 'created');
INSERT INTO INTERNAL_METADATA (ID, GLOSS, FIELD) VALUES (5, 'Subject', 'subject');
INSERT INTO INTERNAL_METADATA (ID, GLOSS, FIELD) VALUES (6, 'Format', 'format');
INSERT INTO INTERNAL_METADATA (ID, GLOSS, FIELD) VALUES (7, 'Language', 'language');
INSERT INTO INTERNAL_METADATA (ID, GLOSS, FIELD) VALUES (8, 'Identifier', 'terms.identifier');
INSERT INTO INTERNAL_METADATA (ID, GLOSS, FIELD) VALUES (9, 'Part Of', 'isPartOf');