INSERT INTO INTERNAL_METADATA (ID, GLOSS, FIELD, REQUIRED) VALUES (1, 'Id', 'id', true);
INSERT INTO INTERNAL_METADATA (ID, GLOSS, FIELD, REQUIRED) VALUES (2, 'Title', 'title', true);
INSERT INTO INTERNAL_METADATA (ID, GLOSS, FIELD, REQUIRED) VALUES (3, 'Creator', 'creator', false);
INSERT INTO INTERNAL_METADATA (ID, GLOSS, FIELD, REQUIRED) VALUES (4, 'Created', 'created', false);
INSERT INTO INTERNAL_METADATA (ID, GLOSS, FIELD, REQUIRED) VALUES (5, 'Subject', 'subject', false);
INSERT INTO INTERNAL_METADATA (ID, GLOSS, FIELD, REQUIRED) VALUES (6, 'Format', 'format', false);
INSERT INTO INTERNAL_METADATA (ID, GLOSS, FIELD, REQUIRED) VALUES (7, 'Language', 'language', false);
INSERT INTO INTERNAL_METADATA (ID, GLOSS, FIELD, REQUIRED) VALUES (8, 'Identifier', 'terms.identifier', false);
INSERT INTO INTERNAL_METADATA (ID, GLOSS, FIELD, REQUIRED) VALUES (9, 'Part Of', 'isPartOf', false);