name: TAMULib NodeJs Coverage Action
description: Build coverage for NodeJs code for parallel coveralls execution.

inputs:
  nodejs-version:
    description: 'The version of NodeJs to use.'
    required: true
    default: 12
  coveralls-token:
    description: 'The API token for Coveralls.'
    required: false
  build-number:
    description: 'The Unique Build Number for Coveralls.'
    required: true
  github-token:
    description: 'The API token for Github.'
    required: true

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v2

    - name: Install NodeJs
      uses: actions/setup-node@v2
      run: npm install

    - name: Setup NodeJs ${{ inputs.nodejs-version }}
      env:
        COVERALLS_PARALLEL: true
        COVERALLS_BUILD_NUMBER: run-${{ inputs.build_number }}-java
        COVERALLS_REPO_TOKEN: ${{ inputs.coveralls_token }}
      run: |
        npm start > /dev/null &
        npm run update-webdriver
        sleep 1 # give server time to start
        grunt coverage-preprocess
        npm run test-ci
        grunt coverage

    - name: Coveralls Parallel NodeJs
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ inputs.github_token }}
        flag-name: run-${{ inputs.build_number }}-java
        parallel: true
