name: Cache-Java_Build

on: [ workflow_dispatch ]

jobs:
  cache:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Node Cache"
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-cache-node-${{ hashFiles('**/package.json', '**/package-lock.json') }}

      - name: "Node Cache Modules"
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-cache-node_modules-${{ hashFiles('**/package.json', '**/package-lock.json') }}

      - name: "Maven Cache"
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-cache-maven-${{ hashFiles('**/pom.xml') }}

      - name: "Setup Node"
        uses: actions/setup-node@v2
        with:
          node-version: 10

      - name: "Setup Java"
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: "Maven Build"
        run: mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
