name: CI

on:
  push:
    branches: [ $default-branch ]

  pull_request:
    branches: [ $default-branch ]

  workflow_dispatch:

jobs:
  build-all:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 2
      matrix:
        language-engine: [ java, nodejs ]

        include:
          - language-engine: java
            uses: ./.github/actions/coveralls-java
            with: java-version
            version: 1.8

          - language-engine: nodejs
            with: node-version
            uses: ./.github/actions/coveralls-nodejs
            version: 12

    steps:
      - uses: actions/checkout@v2
      - uses: ${{ matrix.uses }}
        with:
          version: ${{ matrix.version }}
          coveralls-token: ${{ secrets.coveralls_token }}
          build-number: ${{ github.run_number }}

      - if: ${{ language-engine == 'java' }}
        uses: ./.github/actions/ghpages-deploy

  finish:
    needs: build-all
    runs-on: ubuntu-latest

    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
      run: curl https://coveralls.io/webhook?repo_token=${{ secrets.coveralls_token }}
