name: TAMULib Sage GH-Pages

on:
  push:
    branches:
      - $default_branch

  workflow_dispatch:

jobs:
  ghpages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Cache Maven Dependencies"
        uses: actions/cache@v2
        env:
          cache-name: sage-cache-maven-dependencies
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-sage-cache-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-sage-cache-maven-${{ hashFiles('**/pom.xml') }}

      - name: "Setup Java"
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: "Fixing node_modules Path for Java"
        run: sudo chown $RUNNER_USER /usr/local/lib/node_modules/

      - name: "Compiling Tests for Java"
        run: mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V

      - name: "Running Tests for Java"
        run: mvn clean test cobertura:cobertura jacoco:report coveralls:report -DdryRun=true

      - name: "Deploy GH-Pages"
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          github_token: ${{ secrets.github_token }}
          branch: gh-pages
          folder: target/generated-docs
          clean: true
          single_commit: true
