name: Java CI with Maven

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 10.x

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Tests with Coveralls coverage reports
        run: mvn clean test cobertura:cobertura jacoco:report coveralls:report -DdryRun=true -DtestClient

      - name: Send Java Coveralls coverage report
        uses: MikeEdgar/github-action@raw_coverage_file
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: java-${{ github.action }}-${{ github.run_number }}
          parallel: true
          path-to-file: ./target/coveralls.json
          coverage-format: raw

      - name: Send Node Coveralls coverage report
        uses: MikeEdgar/github-action@raw_coverage_file
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: node-${{ github.action }}-${{ github.run_number }}
          parallel: true
          path-to-lcov: ./src/main/webapp/coverage/coveralls.json
          coverage-format: raw

      - name: Coveralls finished
        uses: MikeEdgar/github-action@raw_coverage_file
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true

      - name: Deploy to GitHub pages
        if: github.event.push.base.ref == 'master'
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: target/generated-docs
          CLEAN: true
          SINGLE_COMMIT: true
